bug/urls.py
from django.urls import path

from . import views

app_name = "bug"
urlpatterns = [
    path("", views.get_all_bugs, name="get_all_bugs"),
    path("<int:bug_id>/", views.bug_detail, name="bug_detail"),
    path("register-bug", views.register_bug, name="register_bug")
]

bugsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("bug/", include("bug.urls")),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bug/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# bug model
class Bug(models.Model):
    """
    A model to represent a bug report in the bug tracking system.

    Attributes:
        description (str): A textual description of the bug.
        bug_type (str): The type of the bug (e.g., 'error', 'feature', 'other').
        report_datetime (datetime): The date and time when the bug is registered.
        status (str): The status of the bug resolution (e.g., 'to_do', 'in_progress', 'done').
    """
    # allowed descriptions of bug types
    BUG_TYPES = (
        ('error', _('Error')),
        ('feature', _('New Feature')),
        ('other', _('Other')),
    )

    # allowed bug status choices
    STATUS_CHOICES = (
        ('to_do', _('To Do')),
        ('in_progress', _('In Progress')),
        ('done', _('Done')),
    )

    description = models.CharField(max_length=120)
    bug_type = models.CharField(
        max_length=70, choices=BUG_TYPES, default='error')
    report_date = models.DateField(auto_now_add=True)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='to_do')

    def __str__(self):
        """
        Creates a human-readable representation of the bug.

        Returns:
            str: The bug's description.
        """
        return self.description

bug/forms.py
from django.forms import ModelForm, Textarea
from django.utils.translation import gettext_lazy as _

from .models import Bug


class BugForm(ModelForm):
    """
    Form class for creating and validating a Bug.
    """

    class Meta:
        """
        Metadata options for the BugForm class.

        Attributes:
            model (Bug): The model associated with this form.
            fields (list): The fields from the model to include in the form.
            widgets (dict): Custom widgets for form fields.
            error_messages (dict): Custom error messages for form fields.
        """
        model = Bug
        fields = ['description', 'bug_type', 'status']
        widgets = {
            "description": Textarea(attrs={"cols": 80, "rows": 3}),
        }
        error_messages = {
            "description": {
                "max_length": _("description is too long"),
            },
        }

bug/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.urls import reverse

# import the model
from .models import Bug

from .forms import BugForm


def register_bug(request):
    """
    Renders the bug registration page.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponseRedirect: List of all the bugs including the one added
    """
    if request.method == 'POST':
        form = BugForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('bug:get_all_bugs'))
    else:
        form = BugForm()

    return render(request, 'bug/register.html', {'form': form})


def bug_detail(request, bug_id):
    """
    Renders the bug detail page for a specific bug.

    Args:
        request (HttpRequest): The HTTP request object.
        bug_id (int): The ID of the bug to display details for.

    Returns:
        HttpResponse: The rendered bug detail page.

    Raises:
        Http404: If the specified bug_id does not exist in the database.
    """
    bug = get_object_or_404(Bug, pk=bug_id)

    return render(request, "bug/detail.html", {"bug": bug})


def get_all_bugs(request):
    """
    Displays a list of all bugs with the most recent bug appearing at the top.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The rendered page with a list of bugs.
    """
    bugs_list = Bug.objects.all().order_by("-report_date")
    context = {"bugs_list": bugs_list}

    return render(request, "bug/index.html", context)

bug/templates/base.html
<!-- 
    base html template to be inherited by the rest of the templates
 -->

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>{% block title %}Bugs{% endblock %}</title>
</head>

<body>
    <div class="container">
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>

</html>

bug/templates/bug/detail.html
<!-- 
    lists all the attributes of a bug
 -->

{% extends "base.html" %}
{% block title %}Bug detail{% endblock %}
{% block content %}
<h1>Bug Detail</h1>
<ul>
    <li><strong>Description:</strong> {{ bug.description }}</li>
    <li><strong>Type:</strong> {{ bug.get_bug_type_display }}</li>
    <li><strong>Report Date:</strong> {{ bug.report_date }}</li>
    <li><strong>Status:</strong> {{ bug.get_status_display }}</li>
</ul>
{% endblock %}

bug/templates/bug/index.html
<!-- 
    lists all bugs
 -->

{% extends "base.html" %}

{% load static %}

{% block content %}
<button class="register"><a href="{%url 'bug:register_bug' %}">register a bug</a></button>
<h1>All bugs</h1>
{% if bugs_list %}
<ul>
    {% for bug in bugs_list %}
    <li class="list"><a href="{%url 'bug:bug_detail' bug.id%}">{{ bug.description }} <small>- {{bug.report_date}}</small></a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No bugs registered yet!</p>
{% endif %}
{% endblock %}

bug/templates/bug/register.html
<!-- 
    form to register a new bug
 -->

{% extends "base.html" %}
{% block title %}register bug{% endblock %}
{% block content %}
<h1>Register a Bug</h1>
<form action="{%url 'bug:register_bug'%}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="field-wrapper">
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
            <small class="error">
                {{ field.errors }}
            </small>
        {% endif %}
    </div>
    {% endfor %}
    <button type="submit">Submit Bug</button>
</form>
{% endblock %}